/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TinyMerkleTree,
  TinyMerkleTreeInterface,
} from "../TinyMerkleTree";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "last32Roots",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "root",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TinyMerkleTree__factory {
  static readonly abi = _abi;
  static createInterface(): TinyMerkleTreeInterface {
    return new Interface(_abi) as TinyMerkleTreeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TinyMerkleTree {
    return new Contract(address, _abi, runner) as unknown as TinyMerkleTree;
  }
}
