/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "PoseidonT2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT2__factory>;
    getContractFactory(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT3__factory>;
    getContractFactory(
      name: "TinyMerkleTree",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TinyMerkleTree__factory>;
    getContractFactory(
      name: "TMT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TMT__factory>;

    getContractAt(
      name: "PoseidonT2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT2>;
    getContractAt(
      name: "PoseidonT3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT3>;
    getContractAt(
      name: "TinyMerkleTree",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TinyMerkleTree>;
    getContractAt(
      name: "TMT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TMT>;

    deployContract(
      name: "PoseidonT2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT2>;
    deployContract(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;
    deployContract(
      name: "TinyMerkleTree",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TinyMerkleTree>;
    deployContract(
      name: "TMT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TMT>;

    deployContract(
      name: "PoseidonT2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT2>;
    deployContract(
      name: "PoseidonT3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;
    deployContract(
      name: "TinyMerkleTree",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TinyMerkleTree>;
    deployContract(
      name: "TMT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TMT>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
