/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TMTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_LEAVES_LENGTH"
      | "STORED_ROOT_LENGTH"
      | "addLeaf"
      | "depthHashes"
      | "depthLengths"
      | "last32Roots"
      | "length"
      | "root"
      | "rootIndex"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LeafAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_LEAVES_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STORED_ROOT_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addLeaf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "depthHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depthLengths",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "last32Roots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "length", values?: undefined): string;
  encodeFunctionData(functionFragment: "root", values?: undefined): string;
  encodeFunctionData(functionFragment: "rootIndex", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_LEAVES_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STORED_ROOT_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addLeaf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depthHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depthLengths",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "last32Roots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "length", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "root", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rootIndex", data: BytesLike): Result;
}

export namespace LeafAddedEvent {
  export type InputTuple = [leaf: BytesLike];
  export type OutputTuple = [leaf: string];
  export interface OutputObject {
    leaf: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TMT extends BaseContract {
  connect(runner?: ContractRunner | null): TMT;
  waitForDeployment(): Promise<this>;

  interface: TMTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_LEAVES_LENGTH: TypedContractMethod<[], [bigint], "view">;

  STORED_ROOT_LENGTH: TypedContractMethod<[], [bigint], "view">;

  addLeaf: TypedContractMethod<[s: string], [void], "nonpayable">;

  depthHashes: TypedContractMethod<[depth: BigNumberish], [string], "view">;

  depthLengths: TypedContractMethod<[depth: BigNumberish], [bigint], "view">;

  last32Roots: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  length: TypedContractMethod<[], [bigint], "view">;

  root: TypedContractMethod<[], [string], "view">;

  rootIndex: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_LEAVES_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STORED_ROOT_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLeaf"
  ): TypedContractMethod<[s: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depthHashes"
  ): TypedContractMethod<[depth: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "depthLengths"
  ): TypedContractMethod<[depth: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "last32Roots"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "length"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "root"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rootIndex"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LeafAdded"
  ): TypedContractEvent<
    LeafAddedEvent.InputTuple,
    LeafAddedEvent.OutputTuple,
    LeafAddedEvent.OutputObject
  >;

  filters: {
    "LeafAdded(bytes32)": TypedContractEvent<
      LeafAddedEvent.InputTuple,
      LeafAddedEvent.OutputTuple,
      LeafAddedEvent.OutputObject
    >;
    LeafAdded: TypedContractEvent<
      LeafAddedEvent.InputTuple,
      LeafAddedEvent.OutputTuple,
      LeafAddedEvent.OutputObject
    >;
  };
}
